I0113 20:46:24.050942       1 serving.go:348] Generated self-signed cert in-memory
W0113 20:46:32.570259       1 requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
W0113 20:46:32.571020       1 authentication.go:346] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W0113 20:46:32.571316       1 authentication.go:347] Continuing without authentication configuration. This may treat all requests as anonymous.
W0113 20:46:32.571748       1 authentication.go:348] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I0113 20:46:32.767740       1 server.go:147] "Starting Kubernetes Scheduler" version="v1.24.7"
I0113 20:46:32.767834       1 server.go:149] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0113 20:46:33.077879       1 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0113 20:46:33.078691       1 secure_serving.go:210] Serving securely on 127.0.0.1:10259
I0113 20:46:33.079274       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0113 20:46:33.081585       1 shared_informer.go:255] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0113 20:46:33.187983       1 shared_informer.go:262] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0113 20:46:33.280444       1 leaderelection.go:248] attempting to acquire leader lease kube-system/kube-scheduler...
I0113 20:46:49.537809       1 leaderelection.go:258] successfully acquired lease kube-system/kube-scheduler
E0113 23:01:04.495984       1 event_broadcaster.go:253] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nginx-deployment-6dccd8f6b9-fw6zp.17aa0a69ca276ca0", GenerateName:"", Namespace:"default", SelfLink:"", UID:"8ebb331c-cd32-4417-a88a-7b3561ea24a3", ResourceVersion:"11136012", Generation:0, CreationTimestamp:time.Date(2024, time.January, 13, 23, 0, 58, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kube-scheduler", Operation:"Update", APIVersion:"events.k8s.io/v1", Time:time.Date(2024, time.January, 13, 23, 0, 58, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0008cc150), Subresource:""}}}, EventTime:time.Date(2024, time.January, 13, 23, 0, 58, 392549021, time.Local), Series:(*v1.EventSeries)(0xc00042d420), ReportingController:"default-scheduler", ReportingInstance:"default-scheduler-kind-control-plane", Action:"Scheduling", Reason:"FailedScheduling", Regarding:v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-deployment-6dccd8f6b9-fw6zp", UID:"b684ab2c-a732-4570-b0e1-32adcdc60e09", APIVersion:"v1", ResourceVersion:"11136002", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 2 Insufficient cpu. preemption: 0/3 nodes are available: 1 Preemption is not helpful for scheduling, 2 No preemption victims found for incoming pod.", Type:"Warning", DeprecatedSource:v1.EventSource{Component:"", Host:""}, DeprecatedFirstTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedLastTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedCount:0}': 'Event "nginx-deployment-6dccd8f6b9-fw6zp.17aa0a69ca276ca0" is invalid: series.count: Invalid value: "": should be at least 2' (will not retry!)
E0113 23:10:32.836234       1 event_broadcaster.go:253] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nginx-deployment-6dccd8f6b9-fw6zp.17aa0a69ca276ca0", GenerateName:"", Namespace:"default", SelfLink:"", UID:"8ebb331c-cd32-4417-a88a-7b3561ea24a3", ResourceVersion:"11136012", Generation:0, CreationTimestamp:time.Date(2024, time.January, 13, 23, 0, 58, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kube-scheduler", Operation:"Update", APIVersion:"events.k8s.io/v1", Time:time.Date(2024, time.January, 13, 23, 0, 58, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0008cc150), Subresource:""}}}, EventTime:time.Date(2024, time.January, 13, 23, 0, 58, 392549021, time.Local), Series:(*v1.EventSeries)(0xc00042d420), ReportingController:"default-scheduler", ReportingInstance:"default-scheduler-kind-control-plane", Action:"Scheduling", Reason:"FailedScheduling", Regarding:v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-deployment-6dccd8f6b9-fw6zp", UID:"b684ab2c-a732-4570-b0e1-32adcdc60e09", APIVersion:"v1", ResourceVersion:"11136002", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 2 Insufficient cpu. preemption: 0/3 nodes are available: 1 Preemption is not helpful for scheduling, 2 No preemption victims found for incoming pod.", Type:"Warning", DeprecatedSource:v1.EventSource{Component:"", Host:""}, DeprecatedFirstTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedLastTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedCount:0}': 'Event "nginx-deployment-6dccd8f6b9-fw6zp.17aa0a69ca276ca0" is invalid: series.count: Invalid value: "": should be at least 2' (will not retry!)
